In [1]:
import numpy as np
import matplotlib.pylab as plt

In [2]:
def step_function(x):
    if x > 0:
        return 1
    else:
        return 0

In [3]:
def step_function2(x):
    return np.array(x > 0, dtype=np.int)


In [4]:
def step_graph():
    x = np.arange(-5.0, 5.0, 0.1)
    y = step_function2(x)
    plt.plot(x, y)
    plt.ylim(-0.1, 1.1)
    plt.show()

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [8]:
def sigmoid_graph():
    x = np.arange(-5.0, 5.0, 0.1)
    y = sigmoid(x)
    plt.plot(x, y)
    plt.ylim(-0.1, 1.1)
    plt.show()


In [ ]:
step_graph()

In [9]:
sigmoid_graph()

SystemExit: 0

To exit: use 'exit', 'quit', or Ctrl-D.


In [12]:
A = np.array([[1,2], [3,4]])
A.shape

(2, 2)

In [13]:
B = np.array([[5,6], [7,8]])
B.shape

(2, 2)

In [14]:
np.dot(A, B) # 内積、ドット積

array([[19, 22],
       [43, 50]])

In [42]:
# start init_network

In [15]:
X = np.array([1.0, 0.5])

In [16]:
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])

In [17]:
B1 = np.array([0.1, 0.2, 0.3])

In [21]:
W1.shape

(2, 3)

In [19]:
X.shape

(2,)

In [20]:
B1.shape

(3,)

In [22]:
A1 = np.dot(X, W1) + B1

In [23]:
print(A1)

[ 0.3  0.7  1.1]


In [24]:
Z1 = sigmoid(A1)

In [43]:
print(Z1)

[ 0.57444252  0.66818777  0.75026011]


In [ ]:
# start forward

In [26]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])

In [27]:
B2 = np.array([0.1, 0.2])

In [30]:
Z1.shape

(3,)

In [29]:
W2.shape

(3, 2)

In [31]:
B2.shape

(2,)

In [32]:
A2 = np.dot(Z1, W2) + B2

In [33]:
Z2 = sigmoid(A2)

In [34]:
print(A2)

[ 0.51615984  1.21402696]


In [35]:
print(Z2)

[ 0.62624937  0.7710107 ]


In [36]:
def identity_function(x):
    return x

In [37]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])

In [38]:
B3 = np.array([0.1, 0.2])

In [39]:
A3 = np.dot(Z2, W3) + B3

In [40]:
Y = identity_function(A3)

In [41]:
print(Y)

[ 0.31682708  0.69627909]
